export const TasksActionTypes = {
  ADD_TASK: 'ADD_TASK',
  REMOVE_TASK: 'REMOVE_TASK',
  LOAD_DUMMY_DATA_START: 'LOAD_DUMMY_DATA_START',
  LOAD_DUMMY_DATA_SUCCESS: 'LOAD_DUMMY_DATA_SUCCESS',
  LOAD_DUMMY_DATA_FAILURE: 'LOAD_DUMMY_DATA_FAILURE'
};